defaults: &defaults
  docker:
    - image: circleci/clojure:openjdk-15-lein-2.9.5-buster

  working_directory: ~/repo

  environment:
    LEIN_ROOT: "true"
    JVM_OPTS: -XX:MaxRAMPercentage=85

version: 2.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein smoke